package bootstrap

import (
	"net/http"

	"admin_back_go/internal/middleware"
)

func permissionRouteRules() map[middleware.RouteKey]string {
	return map[middleware.RouteKey]string{
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/permissions"):                               "permission_permission_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/permissions/:id"):                            "permission_permission_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/permissions/:id/status"):                   "permission_permission_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/permissions/:id"):                         "permission_permission_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/permissions"):                             "permission_permission_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/roles"):                                     "permission_role_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/roles/:id"):                                  "permission_role_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/roles/:id/default"):                        "permission_role_setDefault",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/roles/:id"):                               "permission_role_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/roles"):                                   "permission_role_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/auth-platforms"):                            "permission_authPlatform_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/auth-platforms/:id"):                         "permission_authPlatform_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/auth-platforms/:id/status"):                "permission_authPlatform_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/auth-platforms/:id"):                      "permission_authPlatform_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/auth-platforms"):                          "permission_authPlatform_del",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/users/:id"):                                  "user_userManager_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/users/:id/status"):                         "user_userManager_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/users"):                                    "user_userManager_batchEdit",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/users/export"):                              "user_userManager_export",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/users/:id"):                               "user_userManager_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/users"):                                   "user_userManager_del",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/user-sessions/:id/revoke"):                 "user_userManager_kick",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/user-sessions/revoke"):                     "user_userManager_kick",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/operation-logs/:id"):                      "devTools_operationLog_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/operation-logs"):                          "devTools_operationLog_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/system-settings"):                           "system_setting_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/system-settings/:id"):                        "system_setting_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/system-settings/:id/status"):               "system_setting_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/system-settings/:id"):                     "system_setting_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/system-settings"):                         "system_setting_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/upload-drivers"):                            "system_uploadConfig_driverAdd",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/upload-drivers/:id"):                         "system_uploadConfig_driverEdit",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-drivers/:id"):                      "system_uploadConfig_driverDel",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-drivers"):                          "system_uploadConfig_driverDel",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/upload-rules"):                              "system_uploadConfig_ruleAdd",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/upload-rules/:id"):                           "system_uploadConfig_ruleEdit",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-rules/:id"):                        "system_uploadConfig_ruleDel",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-rules"):                            "system_uploadConfig_ruleDel",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/upload-settings"):                           "system_uploadConfig_settingAdd",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/upload-settings/:id"):                        "system_uploadConfig_settingEdit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/upload-settings/:id/status"):               "system_uploadConfig_settingStatus",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-settings/:id"):                     "system_uploadConfig_settingDel",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-settings"):                         "system_uploadConfig_settingDel",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/system-logs/files"):                          "system_log_files",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/system-logs/files/:name/lines"):              "system_log_content",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/notification-tasks"):                        "system_notificationTask_add",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/notification-tasks/:id/cancel"):            "system_notificationTask_cancel",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/notification-tasks/:id"):                  "system_notificationTask_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/cron-tasks"):                                "devTools_cronTask_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/cron-tasks/:id"):                             "devTools_cronTask_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/cron-tasks/:id/status"):                    "devTools_cronTask_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/cron-tasks/:id"):                          "devTools_cronTask_del",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/cron-tasks"):                              "devTools_cronTask_del",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/cron-tasks/:id/logs"):                        "devTools_cronTask_logs",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/channels/page-init"):                 "payment_channel_list",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/channels"):                           "payment_channel_list",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/payment/channels"):                          "payment_channel_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/payment/channels/:id"):                       "payment_channel_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/payment/channels/:id/status"):              "payment_channel_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/payment/channels/:id"):                    "payment_channel_del",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/orders/page-init"):                   "payment_order_list",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/orders"):                             "payment_order_list",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/orders/:order_no"):                   "payment_order_list",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/payment/orders/:order_no/close"):           "payment_order_close",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/events"):                             "payment_event_list",
		middleware.NewRouteKey(http.MethodGet, "/api/admin/v1/payment/events/:id"):                         "payment_event_list",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/client-versions"):                           "system_clientVersion_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/client-versions/:id"):                        "system_clientVersion_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/client-versions/:id/latest"):               "system_clientVersion_setLatest",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/client-versions/:id/force-update"):         "system_clientVersion_forceUpdate",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/client-versions/:id"):                     "system_clientVersion_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers/model-options"):                "ai_provider_test",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers"):                              "ai_provider_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-providers/:id"):                           "ai_provider_edit",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers/:id/test"):                     "ai_provider_test",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers/:id/sync-models"):              "ai_provider_test",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-providers/:id/models"):                    "ai_provider_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-providers/:id/status"):                  "ai_provider_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-providers/:id"):                        "ai_provider_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-agents"):                                 "ai_agent_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-agents/:id"):                              "ai_agent_edit",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-agents/:id/test"):                        "ai_agent_test",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-agents/:id/status"):                     "ai_agent_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-agents/:id"):                           "ai_agent_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-agents/:id/bindings"):                    "ai_agent_binding_add",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-agent-bindings/:id"):                   "ai_agent_binding_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-maps"):                         "ai_knowledge_map_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-knowledge-maps/:id"):                      "ai_knowledge_map_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-knowledge-maps/:id/status"):             "ai_knowledge_map_status",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-maps/:id/sync"):                "ai_knowledge_map_sync",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-knowledge-maps/:id"):                   "ai_knowledge_map_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-maps/:id/documents"):           "ai_knowledge_map_document_add",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-knowledge-documents/:id/status"):        "ai_knowledge_map_document_status",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-documents/:id/refresh-status"): "ai_knowledge_map_document_refresh",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-knowledge-documents/:id"):              "ai_knowledge_map_document_del",
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-tool-maps"):                              "ai_tool_map_add",
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-tool-maps/:id"):                           "ai_tool_map_edit",
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-tool-maps/:id/status"):                  "ai_tool_map_status",
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-tool-maps/:id"):                        "ai_tool_map_del",
	}
}

func operationRouteRules() map[middleware.RouteKey]middleware.OperationRule {
	return map[middleware.RouteKey]middleware.OperationRule{
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/permissions"): {
			Module: "permission",
			Action: "create",
			Title:  "新增权限",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/permissions/:id"): {
			Module: "permission",
			Action: "update",
			Title:  "编辑权限",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/permissions/:id/status"): {
			Module: "permission",
			Action: "change_status",
			Title:  "修改权限状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/permissions/:id"): {
			Module: "permission",
			Action: "delete",
			Title:  "删除权限",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/permissions"): {
			Module: "permission",
			Action: "delete_batch",
			Title:  "批量删除权限",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/roles"): {
			Module: "role",
			Action: "create",
			Title:  "新增角色",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/roles/:id"): {
			Module: "role",
			Action: "update",
			Title:  "编辑角色",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/roles/:id/default"): {
			Module: "role",
			Action: "set_default",
			Title:  "设置默认角色",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/roles/:id"): {
			Module: "role",
			Action: "delete",
			Title:  "删除角色",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/roles"): {
			Module: "role",
			Action: "delete_batch",
			Title:  "批量删除角色",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/auth-platforms"): {
			Module: "auth_platform",
			Action: "create",
			Title:  "新增认证平台",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/auth-platforms/:id"): {
			Module: "auth_platform",
			Action: "update",
			Title:  "编辑认证平台",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/auth-platforms/:id/status"): {
			Module: "auth_platform",
			Action: "change_status",
			Title:  "修改认证平台状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/auth-platforms/:id"): {
			Module: "auth_platform",
			Action: "delete",
			Title:  "删除认证平台",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/auth-platforms"): {
			Module: "auth_platform",
			Action: "delete_batch",
			Title:  "批量删除认证平台",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/users/:id"): {
			Module: "user",
			Action: "update",
			Title:  "编辑用户",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/users/:id/status"): {
			Module: "user",
			Action: "change_status",
			Title:  "修改用户状态",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/users"): {
			Module: "user",
			Action: "batch_update_profile",
			Title:  "批量修改用户资料",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/users/export"): {
			Module: "user",
			Action: "export",
			Title:  "用户导出",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/users/:id"): {
			Module: "user",
			Action: "delete",
			Title:  "删除用户",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/users"): {
			Module: "user",
			Action: "delete_batch",
			Title:  "批量删除用户",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/user-sessions/:id/revoke"): {
			Module: "user_session",
			Action: "revoke",
			Title:  "踢下线用户会话",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/user-sessions/revoke"): {
			Module: "user_session",
			Action: "revoke_batch",
			Title:  "批量踢下线用户会话",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/export-tasks/:id"): {
			Module: "export_task",
			Action: "delete",
			Title:  "删除导出任务",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/export-tasks"): {
			Module: "export_task",
			Action: "delete_batch",
			Title:  "批量删除导出任务",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/profile"): {
			Module: "profile",
			Action: "update_profile",
			Title:  "编辑个人资料",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/profile/security/password"): {
			Module: "profile_security",
			Action: "update_password",
			Title:  "修改登录密码",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/profile/security/email"): {
			Module: "profile_security",
			Action: "update_email",
			Title:  "绑定或换绑邮箱",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/profile/security/phone"): {
			Module: "profile_security",
			Action: "update_phone",
			Title:  "绑定或换绑手机号",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/operation-logs/:id"): {
			Module: "operation_log",
			Action: "delete",
			Title:  "删除操作日志",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/operation-logs"): {
			Module: "operation_log",
			Action: "delete_batch",
			Title:  "批量删除操作日志",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/system-settings"): {
			Module: "system_setting",
			Action: "create",
			Title:  "新增系统设置",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/system-settings/:id"): {
			Module: "system_setting",
			Action: "update",
			Title:  "编辑系统设置",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/system-settings/:id/status"): {
			Module: "system_setting",
			Action: "change_status",
			Title:  "修改系统设置状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/system-settings/:id"): {
			Module: "system_setting",
			Action: "delete",
			Title:  "删除系统设置",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/system-settings"): {
			Module: "system_setting",
			Action: "delete_batch",
			Title:  "批量删除系统设置",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/upload-drivers"): {
			Module: "upload_driver",
			Action: "create",
			Title:  "新增上传驱动",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/upload-drivers/:id"): {
			Module: "upload_driver",
			Action: "update",
			Title:  "编辑上传驱动",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-drivers/:id"): {
			Module: "upload_driver",
			Action: "delete",
			Title:  "删除上传驱动",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-drivers"): {
			Module: "upload_driver",
			Action: "delete_batch",
			Title:  "批量删除上传驱动",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/upload-rules"): {
			Module: "upload_rule",
			Action: "create",
			Title:  "新增上传规则",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/upload-rules/:id"): {
			Module: "upload_rule",
			Action: "update",
			Title:  "编辑上传规则",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-rules/:id"): {
			Module: "upload_rule",
			Action: "delete",
			Title:  "删除上传规则",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-rules"): {
			Module: "upload_rule",
			Action: "delete_batch",
			Title:  "批量删除上传规则",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/upload-settings"): {
			Module: "upload_setting",
			Action: "create",
			Title:  "新增上传设置",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/upload-settings/:id"): {
			Module: "upload_setting",
			Action: "update",
			Title:  "编辑上传设置",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/upload-settings/:id/status"): {
			Module: "upload_setting",
			Action: "change_status",
			Title:  "修改上传设置状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-settings/:id"): {
			Module: "upload_setting",
			Action: "delete",
			Title:  "删除上传设置",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/upload-settings"): {
			Module: "upload_setting",
			Action: "delete_batch",
			Title:  "批量删除上传设置",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/notification-tasks"): {
			Module: "notification_task",
			Action: "create",
			Title:  "发布通知任务",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/notification-tasks/:id/cancel"): {
			Module: "notification_task",
			Action: "cancel",
			Title:  "取消通知任务",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/notification-tasks/:id"): {
			Module: "notification_task",
			Action: "delete",
			Title:  "删除通知任务",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/cron-tasks"): {
			Module: "cron_task",
			Action: "create",
			Title:  "新增定时任务",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/cron-tasks/:id"): {
			Module: "cron_task",
			Action: "update",
			Title:  "编辑定时任务",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/cron-tasks/:id/status"): {
			Module: "cron_task",
			Action: "change_status",
			Title:  "修改定时任务状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/cron-tasks/:id"): {
			Module: "cron_task",
			Action: "delete",
			Title:  "删除定时任务",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/cron-tasks"): {
			Module: "cron_task",
			Action: "delete_batch",
			Title:  "批量删除定时任务",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/payment/channels"): {
			Module: "payment_channel",
			Action: "create",
			Title:  "新增支付渠道",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/payment/channels/:id"): {
			Module: "payment_channel",
			Action: "update",
			Title:  "编辑支付渠道",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/payment/channels/:id/status"): {
			Module: "payment_channel",
			Action: "change_status",
			Title:  "切换支付渠道状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/payment/channels/:id"): {
			Module: "payment_channel",
			Action: "delete",
			Title:  "删除支付渠道",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/payment/orders/:order_no/close"): {
			Module: "payment_order",
			Action: "close",
			Title:  "关闭支付订单",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/client-versions"): {
			Module: "client_version",
			Action: "create",
			Title:  "发布客户端版本",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/client-versions/:id"): {
			Module: "client_version",
			Action: "update",
			Title:  "编辑客户端版本",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/client-versions/:id/latest"): {
			Module: "client_version",
			Action: "set_latest",
			Title:  "设为最新版本",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/client-versions/:id/force-update"): {
			Module: "client_version",
			Action: "force_update",
			Title:  "切换强制更新",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/client-versions/:id"): {
			Module: "client_version",
			Action: "delete",
			Title:  "删除客户端版本",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers/model-options"): {
			Module: "ai_provider",
			Action: "preview_models",
			Title:  "拉取AI供应商模型",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers"): {
			Module: "ai_provider",
			Action: "create",
			Title:  "新增AI供应商",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-providers/:id"): {
			Module: "ai_provider",
			Action: "update",
			Title:  "编辑AI供应商",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers/:id/test"): {
			Module: "ai_provider",
			Action: "test",
			Title:  "测试AI供应商连接",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-providers/:id/sync-models"): {
			Module: "ai_provider",
			Action: "sync_models",
			Title:  "同步AI供应商模型",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-providers/:id/models"): {
			Module: "ai_provider",
			Action: "update_models",
			Title:  "编辑AI供应商模型",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-providers/:id/status"): {
			Module: "ai_provider",
			Action: "change_status",
			Title:  "修改AI供应商状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-providers/:id"): {
			Module: "ai_provider",
			Action: "delete",
			Title:  "删除AI供应商",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-agents"): {
			Module: "ai_agent",
			Action: "create",
			Title:  "新增AI智能体",
		},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-agents/:id"): {
			Module: "ai_agent",
			Action: "update",
			Title:  "编辑AI智能体",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-agents/:id/test"): {
			Module: "ai_agent",
			Action: "test",
			Title:  "测试AI智能体",
		},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-agents/:id/status"): {
			Module: "ai_agent",
			Action: "change_status",
			Title:  "修改AI智能体状态",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-agents/:id"): {
			Module: "ai_agent",
			Action: "delete",
			Title:  "删除AI智能体",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-agents/:id/bindings"): {
			Module: "ai_agent_binding",
			Action: "create",
			Title:  "新增AI智能体绑定",
		},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-agent-bindings/:id"): {
			Module: "ai_agent_binding",
			Action: "delete",
			Title:  "删除AI智能体绑定",
		},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-maps"):                         {Module: "ai_knowledge_map", Action: "create", Title: "新增AI知识库映射"},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-knowledge-maps/:id"):                      {Module: "ai_knowledge_map", Action: "update", Title: "编辑AI知识库映射"},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-knowledge-maps/:id/status"):             {Module: "ai_knowledge_map", Action: "change_status", Title: "修改AI知识库映射状态"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-maps/:id/sync"):                {Module: "ai_knowledge_map", Action: "sync", Title: "同步AI知识库映射"},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-knowledge-maps/:id"):                   {Module: "ai_knowledge_map", Action: "delete", Title: "删除AI知识库映射"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-maps/:id/documents"):           {Module: "ai_knowledge_document", Action: "create", Title: "新增AI知识库文档映射"},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-knowledge-documents/:id/status"):        {Module: "ai_knowledge_document", Action: "change_status", Title: "修改AI知识库文档状态"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-knowledge-documents/:id/refresh-status"): {Module: "ai_knowledge_document", Action: "refresh_status", Title: "刷新AI知识库文档状态"},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-knowledge-documents/:id"):              {Module: "ai_knowledge_document", Action: "delete", Title: "删除AI知识库文档映射"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-tool-maps"):                              {Module: "ai_tool_map", Action: "create", Title: "新增AI工具映射"},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-tool-maps/:id"):                           {Module: "ai_tool_map", Action: "update", Title: "编辑AI工具映射"},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-tool-maps/:id/status"):                  {Module: "ai_tool_map", Action: "change_status", Title: "修改AI工具映射状态"},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-tool-maps/:id"):                        {Module: "ai_tool_map", Action: "delete", Title: "删除AI工具映射"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-conversations"):                          {Module: "ai_conversation", Action: "create", Title: "新增AI会话"},
		middleware.NewRouteKey(http.MethodPut, "/api/admin/v1/ai-conversations/:id"):                       {Module: "ai_conversation", Action: "update", Title: "编辑AI会话"},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-conversations/:id/status"):              {Module: "ai_conversation", Action: "change_status", Title: "修改AI会话状态"},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-conversations/:id"):                    {Module: "ai_conversation", Action: "delete", Title: "删除AI会话"},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-messages/:id/content"):                  {Module: "ai_message", Action: "edit_content", Title: "编辑AI消息内容"},
		middleware.NewRouteKey(http.MethodPatch, "/api/admin/v1/ai-messages/:id/feedback"):                 {Module: "ai_message", Action: "feedback", Title: "反馈AI消息"},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-messages/:id"):                         {Module: "ai_message", Action: "delete", Title: "删除AI消息"},
		middleware.NewRouteKey(http.MethodDelete, "/api/admin/v1/ai-messages"):                             {Module: "ai_message", Action: "delete_batch", Title: "批量删除AI消息"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-chat/runs"):                              {Module: "ai_chat", Action: "create_run", Title: "创建AI运行"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-chat/messages"):                          {Module: "ai_chat", Action: "send_message", Title: "发送AI消息"},
		middleware.NewRouteKey(http.MethodPost, "/api/admin/v1/ai-chat/runs/:run_id/cancel"):               {Module: "ai_chat", Action: "cancel", Title: "取消AI运行"},
	}
}
