package captcha

import (
	"sync"

	assetimages "github.com/wenlng/go-captcha-assets/resources/imagesv2"
	assettiles "github.com/wenlng/go-captcha-assets/resources/tiles"
	"github.com/wenlng/go-captcha/v2/base/option"
	"github.com/wenlng/go-captcha/v2/slide"
)

// Engine generates raw CAPTCHA images and the server-side answer.
type Engine interface {
	Generate() (*GeneratedChallenge, error)
}

// GeneratedChallenge is the engine output before the answer is persisted.
type GeneratedChallenge struct {
	MasterImage string
	TileImage   string
	TileX       int
	TileY       int
	TileWidth   int
	TileHeight  int
	ImageWidth  int
	ImageHeight int
	Answer      Answer
}

// SlideEngine wraps go-captcha slide mode behind a small project-owned boundary.
type SlideEngine struct {
	captcha slide.Captcha
	mu      sync.Mutex
}

// NewSlideEngine builds the default go-captcha slide engine with embedded assets.
func NewSlideEngine() (*SlideEngine, error) {
	backgrounds, err := assetimages.GetImages()
	if err != nil {
		return nil, err
	}
	tiles, err := assettiles.GetTiles()
	if err != nil {
		return nil, err
	}

	graphs := make([]*slide.GraphImage, 0, len(tiles))
	for _, graph := range tiles {
		graphs = append(graphs, &slide.GraphImage{
			OverlayImage: graph.OverlayImage,
			ShadowImage:  graph.ShadowImage,
			MaskImage:    graph.MaskImage,
		})
	}

	builder := slide.NewBuilder(
		slide.WithImageSize(option.Size{Width: 280, Height: 160}),
		slide.WithRangeGraphSize(option.RangeVal{Min: 42, Max: 52}),
	)
	builder.SetResources(
		slide.WithBackgrounds(backgrounds),
		slide.WithGraphImages(graphs),
	)

	return &SlideEngine{captcha: builder.Make()}, nil
}

// Generate returns a slide challenge generated by go-captcha.
func (e *SlideEngine) Generate() (*GeneratedChallenge, error) {
	if e == nil || e.captcha == nil {
		return nil, ErrEngineNotConfigured
	}

	e.mu.Lock()
	data, err := e.captcha.Generate()
	e.mu.Unlock()
	if err != nil {
		return nil, err
	}

	block := data.GetData()
	masterImage, err := data.GetMasterImage().ToBase64()
	if err != nil {
		return nil, err
	}
	tileImage, err := data.GetTileImage().ToBase64()
	if err != nil {
		return nil, err
	}
	imageSize := e.captcha.GetOptions().GetImageSize()

	return &GeneratedChallenge{
		MasterImage: masterImage,
		TileImage:   tileImage,
		TileX:       block.DX,
		TileY:       block.DY,
		TileWidth:   block.Width,
		TileHeight:  block.Height,
		ImageWidth:  imageSize.Width,
		ImageHeight: imageSize.Height,
		Answer:      Answer{X: block.X, Y: block.Y},
	}, nil
}
