package auth

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"admin_back_go/internal/apperror"
	"admin_back_go/internal/enum"
	"admin_back_go/internal/module/systemsetting"
	"admin_back_go/internal/platform/redisclient"
	sharedsetting "admin_back_go/internal/shared/setting"

	"github.com/redis/go-redis/v9"
	assetimages "github.com/wenlng/go-captcha-assets/resources/imagesv2"
	assettiles "github.com/wenlng/go-captcha-assets/resources/tiles"
	"github.com/wenlng/go-captcha/v2/base/option"
	"github.com/wenlng/go-captcha/v2/slide"
)

const TypeSlide = enum.CaptchaTypeSlide

// Answer is the public user answer submitted with the login request.
type Answer struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// ChallengeResponse is the REST payload for a generated CAPTCHA challenge.
type ChallengeResponse struct {
	CaptchaID   string `json:"captcha_id"`
	CaptchaType string `json:"captcha_type"`
	MasterImage string `json:"master_image"`
	TileImage   string `json:"tile_image"`
	TileX       int    `json:"tile_x"`
	TileY       int    `json:"tile_y"`
	TileWidth   int    `json:"tile_width"`
	TileHeight  int    `json:"tile_height"`
	ImageWidth  int    `json:"image_width"`
	ImageHeight int    `json:"image_height"`
	ExpiresIn   int    `json:"expires_in"`
}

// CaptchaHTTPService is the handler-facing CAPTCHA service boundary.
type CaptchaHTTPService interface {
	Generate(ctx context.Context) (*ChallengeResponse, *apperror.Error)
}

// VerifyInput is the service boundary used by auth login.
type VerifyInput struct {
	ID        string
	Answer    *Answer
	ClientIP  string
	UserAgent string
}

var (
	ErrCaptchaEngineNotConfigured = errors.New("captcha engine is not configured")
	ErrCaptchaStoreNotConfigured  = errors.New("captcha store is not configured")
)

// CaptchaEngine generates raw CAPTCHA images and the server-side answer.
type CaptchaEngine interface {
	Generate() (*GeneratedCaptchaChallenge, error)
}

// GeneratedCaptchaChallenge is the engine output before the answer is persisted.
type GeneratedCaptchaChallenge struct {
	MasterImage string
	TileImage   string
	TileX       int
	TileY       int
	TileWidth   int
	TileHeight  int
	ImageWidth  int
	ImageHeight int
	Answer      Answer
}

// SlideCaptchaEngine wraps go-captcha slide mode behind a small project-owned boundary.
type SlideCaptchaEngine struct {
	captcha slide.Captcha
	mu      sync.Mutex
}

// NewSlideEngine builds the default go-captcha slide engine with embedded assets.
func NewSlideEngine() (*SlideCaptchaEngine, error) {
	backgrounds, err := assetimages.GetImages()
	if err != nil {
		return nil, err
	}
	tiles, err := assettiles.GetTiles()
	if err != nil {
		return nil, err
	}

	graphs := make([]*slide.GraphImage, 0, len(tiles))
	for _, graph := range tiles {
		graphs = append(graphs, &slide.GraphImage{
			OverlayImage: graph.OverlayImage,
			ShadowImage:  graph.ShadowImage,
			MaskImage:    graph.MaskImage,
		})
	}

	builder := slide.NewBuilder(
		slide.WithImageSize(option.Size{Width: 280, Height: 160}),
		slide.WithRangeGraphSize(option.RangeVal{Min: 42, Max: 52}),
	)
	builder.SetResources(
		slide.WithBackgrounds(backgrounds),
		slide.WithGraphImages(graphs),
	)

	return &SlideCaptchaEngine{captcha: builder.Make()}, nil
}

// Generate returns a slide challenge generated by go-captcha.
func (e *SlideCaptchaEngine) Generate() (*GeneratedCaptchaChallenge, error) {
	if e == nil || e.captcha == nil {
		return nil, ErrCaptchaEngineNotConfigured
	}

	e.mu.Lock()
	data, err := e.captcha.Generate()
	e.mu.Unlock()
	if err != nil {
		return nil, err
	}

	block := data.GetData()
	masterImage, err := data.GetMasterImage().ToBase64()
	if err != nil {
		return nil, err
	}
	tileImage, err := data.GetTileImage().ToBase64()
	if err != nil {
		return nil, err
	}
	imageSize := e.captcha.GetOptions().GetImageSize()

	return &GeneratedCaptchaChallenge{
		MasterImage: masterImage,
		TileImage:   tileImage,
		TileX:       block.DX,
		TileY:       block.DY,
		TileWidth:   block.Width,
		TileHeight:  block.Height,
		ImageWidth:  imageSize.Width,
		ImageHeight: imageSize.Height,
		Answer:      Answer{X: block.X, Y: block.Y},
	}, nil
}

const (
	// CaptchaSlidePaddingSettingKey is the system_settings key for tolerated slide-answer offset.
	CaptchaSlidePaddingSettingKey = "auth.captcha.slide_padding"
)

// CaptchaPolicyProvider reads runtime CAPTCHA policy.
type CaptchaPolicyProvider interface {
	TTL(ctx context.Context) (time.Duration, *apperror.Error)
	SlidePadding(ctx context.Context) (int, *apperror.Error)
}

// CaptchaPolicyRepository is the minimal system-setting read boundary CAPTCHA needs.
type CaptchaPolicyRepository interface {
	SettingByKey(ctx context.Context, key string) (*systemsetting.Setting, error)
}

// SystemSettingCaptchaPolicyProvider reads CAPTCHA policy from system_settings.
type SystemSettingCaptchaPolicyProvider struct {
	repository CaptchaPolicyRepository
}

// NewSystemSettingCaptchaPolicyProvider returns a DB-backed CAPTCHA policy provider.
func NewSystemSettingCaptchaPolicyProvider(repository CaptchaPolicyRepository) *SystemSettingCaptchaPolicyProvider {
	return &SystemSettingCaptchaPolicyProvider{repository: repository}
}

// TTL returns the enabled CAPTCHA lifetime.
func (p *SystemSettingCaptchaPolicyProvider) TTL(ctx context.Context) (time.Duration, *apperror.Error) {
	minutes, appErr := sharedsetting.AuthCaptchaTTLMinutes(ctx, p.repository)
	if appErr != nil {
		return 0, appErr
	}
	return time.Duration(minutes) * time.Minute, nil
}

// SlidePadding returns the enabled tolerated slide-answer offset.
func (p *SystemSettingCaptchaPolicyProvider) SlidePadding(ctx context.Context) (int, *apperror.Error) {
	return p.nonNegativeIntSetting(ctx, CaptchaSlidePaddingSettingKey)
}

func (p *SystemSettingCaptchaPolicyProvider) nonNegativeIntSetting(ctx context.Context, key string) (int, *apperror.Error) {
	value, appErr := p.intSetting(ctx, key)
	if appErr != nil {
		return 0, appErr
	}
	if value < 0 {
		return 0, apperror.BadRequestKey("captcha.policy.value_invalid", map[string]any{"key": key}, "验证码策略配置取值无效")
	}
	return value, nil
}

func (p *SystemSettingCaptchaPolicyProvider) intSetting(ctx context.Context, key string) (int, *apperror.Error) {
	if p == nil || p.repository == nil {
		return 0, apperror.InternalKey("captcha.policy.repository_missing", nil, "验证码策略仓储未配置")
	}
	row, err := p.repository.SettingByKey(ctx, key)
	if err != nil {
		return 0, apperror.WrapKey(apperror.CodeInternal, http.StatusInternalServerError, "captcha.policy.query_failed", map[string]any{"key": key}, "查询验证码策略配置失败", err)
	}
	if row == nil || row.IsDel != enum.CommonNo {
		return 0, apperror.InternalKey("captcha.policy.missing", map[string]any{"key": key}, "验证码策略配置缺失")
	}
	if row.Status != enum.CommonYes {
		return 0, apperror.BadRequestKey("captcha.policy.disabled", map[string]any{"key": key}, "验证码策略配置已禁用")
	}
	if row.ValueType != enum.SystemSettingValueNumber {
		return 0, apperror.InternalKey("captcha.policy.type_invalid", map[string]any{"key": key}, "验证码策略配置类型必须为数字")
	}
	value, err := strconv.Atoi(strings.TrimSpace(row.SettingValue))
	if err != nil {
		return 0, apperror.BadRequestKey("captcha.policy.integer_invalid", map[string]any{"key": key}, "验证码策略配置必须为整数")
	}
	return value, nil
}

const defaultCaptchaRedisPrefix = "captcha:slide:"

// CaptchaChallengeSecret is the server-side answer stored with a short TTL.
type CaptchaChallengeSecret struct {
	Answer Answer `json:"answer"`
}

// CaptchaStore persists and consumes CAPTCHA answers.
type CaptchaStore interface {
	Set(ctx context.Context, id string, secret CaptchaChallengeSecret, ttl time.Duration) error
	Take(ctx context.Context, id string) (*CaptchaChallengeSecret, error)
}

// CaptchaRedisStore stores CAPTCHA answers in Redis and consumes them via GETDEL.
type CaptchaRedisStore struct {
	client *redis.Client
	prefix string
}

// NewCaptchaRedisStore returns nil when Redis is not configured.
func NewCaptchaRedisStore(client *redisclient.Client, prefix string) *CaptchaRedisStore {
	if client == nil || client.Redis == nil {
		return nil
	}
	prefix = strings.TrimSpace(prefix)
	if prefix == "" {
		prefix = defaultCaptchaRedisPrefix
	}
	return &CaptchaRedisStore{client: client.Redis, prefix: prefix}
}

// Set stores one challenge answer with the supplied TTL.
func (s *CaptchaRedisStore) Set(ctx context.Context, id string, secret CaptchaChallengeSecret, ttl time.Duration) error {
	if s == nil || s.client == nil {
		return ErrCaptchaStoreNotConfigured
	}
	payload, err := json.Marshal(secret)
	if err != nil {
		return err
	}
	return s.client.Set(ctx, s.key(id), payload, ttl).Err()
}

// Take atomically reads and deletes one challenge answer.
func (s *CaptchaRedisStore) Take(ctx context.Context, id string) (*CaptchaChallengeSecret, error) {
	if s == nil || s.client == nil {
		return nil, ErrCaptchaStoreNotConfigured
	}
	payload, err := s.client.GetDel(ctx, s.key(id)).Result()
	if err == redis.Nil {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var secret CaptchaChallengeSecret
	if err := json.Unmarshal([]byte(payload), &secret); err != nil {
		return nil, err
	}
	return &secret, nil
}

func (s *CaptchaRedisStore) key(id string) string {
	return s.prefix + strings.TrimSpace(id)
}

// CaptchaIDGenerator creates challenge identifiers.
type CaptchaIDGenerator func() (string, error)

// CaptchaService owns CAPTCHA generation and verification.
type CaptchaService struct {
	engine      CaptchaEngine
	store       CaptchaStore
	policy      CaptchaPolicyProvider
	idGenerator CaptchaIDGenerator
}

// CaptchaOption customizes CaptchaService.
type CaptchaOption func(*CaptchaService)

// WithCaptchaIDGenerator injects a challenge ID generator for tests.
func WithCaptchaIDGenerator(generator CaptchaIDGenerator) CaptchaOption {
	return func(service *CaptchaService) {
		if generator != nil {
			service.idGenerator = generator
		}
	}
}

// NewCaptchaService creates a CAPTCHA service.
func NewCaptchaService(engine CaptchaEngine, store CaptchaStore, policy CaptchaPolicyProvider, opts ...CaptchaOption) *CaptchaService {
	service := &CaptchaService{
		engine:      engine,
		store:       store,
		policy:      policy,
		idGenerator: makeCaptchaID,
	}
	for _, opt := range opts {
		opt(service)
	}
	return service
}

// Generate creates a new slide CAPTCHA and stores its answer.
func (s *CaptchaService) Generate(ctx context.Context) (*ChallengeResponse, *apperror.Error) {
	if s == nil || s.engine == nil || s.store == nil || s.policy == nil {
		return nil, apperror.InternalKey("captcha.service_missing", nil, "验证码服务未配置")
	}

	ttl, appErr := s.policy.TTL(ctx)
	if appErr != nil {
		return nil, appErr
	}
	generated, err := s.engine.Generate()
	if err != nil {
		return nil, apperror.InternalKey("captcha.generate_failed", nil, "验证码生成失败")
	}
	id, err := s.idGenerator()
	if err != nil {
		return nil, apperror.InternalKey("captcha.generate_failed", nil, "验证码生成失败")
	}

	if err := s.store.Set(ctx, id, CaptchaChallengeSecret{Answer: generated.Answer}, ttl); err != nil {
		return nil, apperror.InternalKey("captcha.generate_failed", nil, "验证码生成失败")
	}

	return &ChallengeResponse{
		CaptchaID:   id,
		CaptchaType: TypeSlide,
		MasterImage: generated.MasterImage,
		TileImage:   generated.TileImage,
		TileX:       generated.TileX,
		TileY:       generated.TileY,
		TileWidth:   generated.TileWidth,
		TileHeight:  generated.TileHeight,
		ImageWidth:  generated.ImageWidth,
		ImageHeight: generated.ImageHeight,
		ExpiresIn:   int(ttl.Seconds()),
	}, nil
}

// Verify consumes a challenge and validates the submitted slide answer.
func (s *CaptchaService) Verify(ctx context.Context, input VerifyInput) *apperror.Error {
	if s == nil || s.engine == nil || s.store == nil || s.policy == nil {
		return apperror.InternalKey("captcha.service_missing", nil, "验证码服务未配置")
	}
	id := strings.TrimSpace(input.ID)
	if id == "" || input.Answer == nil {
		return apperror.BadRequestKey("captcha.required", nil, "请完成验证码")
	}

	padding, appErr := s.policy.SlidePadding(ctx)
	if appErr != nil {
		return appErr
	}
	secret, err := s.store.Take(ctx, id)
	if err != nil {
		return apperror.InternalKey("captcha.verify_failed", nil, "验证码校验失败")
	}
	if secret == nil {
		return apperror.BadRequestKey("captcha.invalid_or_expired", nil, "验证码错误或已过期")
	}
	if !slide.Validate(input.Answer.X, input.Answer.Y, secret.Answer.X, secret.Answer.Y, padding) {
		return apperror.BadRequestKey("captcha.invalid_or_expired", nil, "验证码错误或已过期")
	}
	return nil
}

func makeCaptchaID() (string, error) {
	raw := make([]byte, 16)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	return hex.EncodeToString(raw), nil
}
