-- AI image playground: agent-driven gpt-image-2 task history and assets.
-- Scope: DB facts only. Provider/model configuration stays in ai_providers / ai_provider_models / ai_agents.

CREATE TABLE IF NOT EXISTS `ai_image_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图片任务ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '发起用户ID',
  `agent_id` BIGINT UNSIGNED NOT NULL COMMENT 'ai_agents.id',
  `agent_name_snapshot` VARCHAR(128) NOT NULL COMMENT '任务创建时智能体名称',
  `provider_id_snapshot` BIGINT UNSIGNED NOT NULL COMMENT '任务创建时供应商ID',
  `provider_name_snapshot` VARCHAR(128) NOT NULL COMMENT '任务创建时供应商名称',
  `model_id_snapshot` VARCHAR(191) NOT NULL COMMENT '任务创建时模型ID',
  `model_display_name_snapshot` VARCHAR(191) NOT NULL DEFAULT '' COMMENT '任务创建时模型展示名',
  `prompt` TEXT NOT NULL COMMENT '图片提示词',
  `size` VARCHAR(32) NOT NULL COMMENT '图片尺寸',
  `quality` VARCHAR(16) NOT NULL COMMENT '质量参数',
  `output_format` VARCHAR(16) NOT NULL COMMENT '输出格式',
  `output_compression` INT UNSIGNED NULL DEFAULT NULL COMMENT '输出压缩率，仅部分格式有效',
  `moderation` VARCHAR(16) NOT NULL COMMENT '安全审核参数',
  `n` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '输出张数',
  `status` VARCHAR(16) NOT NULL COMMENT 'pending/running/success/failed',
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '失败原因',
  `actual_params_json` JSON NULL COMMENT 'provider 实际参数摘要',
  `raw_response_json` JSON NULL COMMENT 'provider 原始响应摘要，不保存图片bytes',
  `is_favorite` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1是2否',
  `finished_at` DATETIME NULL DEFAULT NULL COMMENT '完成时间',
  `elapsed_ms` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
  `is_del` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1删除2正常',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ai_image_tasks_user_created` (`user_id`, `is_del`, `created_at`, `id`),
  KEY `idx_ai_image_tasks_user_status` (`user_id`, `status`, `is_del`, `created_at`, `id`),
  KEY `idx_ai_image_tasks_user_favorite` (`user_id`, `is_favorite`, `is_del`, `created_at`, `id`),
  KEY `idx_ai_image_tasks_agent_created` (`agent_id`, `created_at`, `id`),
  KEY `idx_ai_image_tasks_status_created` (`status`, `created_at`, `id`),
  CONSTRAINT `chk_ai_image_tasks_status` CHECK (`status` IN ('pending', 'running', 'success', 'failed')),
  CONSTRAINT `chk_ai_image_tasks_favorite` CHECK (`is_favorite` IN (1, 2)),
  CONSTRAINT `chk_ai_image_tasks_del` CHECK (`is_del` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI图片生成任务';

CREATE TABLE IF NOT EXISTS `ai_image_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图片资产ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '归属用户ID',
  `storage_provider` VARCHAR(32) NOT NULL COMMENT 'cos/remote_url',
  `storage_key` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '对象存储key',
  `storage_url` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '可访问URL',
  `mime_type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'MIME类型',
  `width` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '图片宽度',
  `height` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '图片高度',
  `size_bytes` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文件字节数',
  `source_type` VARCHAR(16) NOT NULL COMMENT 'upload/mask/generated',
  `is_del` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1删除2正常',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ai_image_assets_user_created` (`user_id`, `is_del`, `created_at`, `id`),
  KEY `idx_ai_image_assets_storage` (`storage_provider`, `storage_key`),
  CONSTRAINT `chk_ai_image_assets_source` CHECK (`source_type` IN ('upload', 'mask', 'generated')),
  CONSTRAINT `chk_ai_image_assets_del` CHECK (`is_del` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI图片资产';

CREATE TABLE IF NOT EXISTS `ai_image_task_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '任务资产关系ID',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT 'ai_image_tasks.id',
  `asset_id` BIGINT UNSIGNED NOT NULL COMMENT 'ai_image_assets.id',
  `role` VARCHAR(16) NOT NULL COMMENT 'input/mask/output',
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `related_asset_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'mask 对应的被编辑资产',
  `actual_params_json` JSON NULL COMMENT '单图实际参数摘要',
  `revised_prompt` TEXT NULL COMMENT 'provider 返回的修订提示词',
  `is_del` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1删除2正常',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ai_image_task_assets_task_role` (`task_id`, `role`, `sort_order`, `id`),
  KEY `idx_ai_image_task_assets_asset` (`asset_id`, `is_del`),
  KEY `idx_ai_image_task_assets_related` (`related_asset_id`),
  CONSTRAINT `fk_ai_image_task_assets_task` FOREIGN KEY (`task_id`) REFERENCES `ai_image_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ai_image_task_assets_asset` FOREIGN KEY (`asset_id`) REFERENCES `ai_image_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_ai_image_task_assets_role` CHECK (`role` IN ('input', 'mask', 'output')),
  CONSTRAINT `chk_ai_image_task_assets_del` CHECK (`is_del` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI图片任务资产关系';
